# Site settings
name: willnorris.com
description: there's more to life than this
url: https://willnorris.com
analytics_id: UA-620101-2
author:
  name: Will Norris
  url: https://willnorris.com/
twitter: "@willnorris"

defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Will Norris
        url: https://willnorris.com/
        photo: https://willnorris.com/logo.jpg
        twitter: "@willnorris"
        google_plus: +willnorris
      twitter_card: summary
  -
    scope:
      path: ""
      type: post
    values:
      layout: post

# Build settings
source: src
destination: public

highlighter: nil
permalink: /:year/:month/:title

sass:
  sass_dir: css
  style: :compressed

markdown: kramdown
kramdown:
  input: GFM
  auto_id_stripping: true
  enable_coderay: false
  hard_wrap: false
