# Site settings
name: willnorris.com
description: there's more to life than this
url: https://willnorris.com
imageproxy_baseurl: /api/imageproxy
short_baseurl: https://wjn.me
analytics_id: UA-620101-2
twitter: "@willnorris"
include:
  - .well-known

collections:
  go_packages:
    output: true
    permalink: /go/:path

defaults:
  -
    scope:
      path: ""
    values:
      author:
        name: Will Norris
        url: https://willnorris.com/
        photo: /logo.jpg
        twitter: "@willnorris"
        google_plus: +willnorris
      twitter_card: summary
      webmention_endpoint: /api/webmention
  -
    scope:
      path: ""
      type: post
    values:
      layout: post
  -
    scope:
      path: ""
      type: go_packages
    values:
      layout: go-package

# Build settings
source: src
destination: public

highlighter: nil
permalink: /:year/:month/:title

sass:
  sass_dir: css
  style: :compressed

markdown: kramdown
kramdown:
  input: GFM
  auto_id_stripping: true
  enable_coderay: false
  hard_wrap: false
